### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by vertices-cpp** [hvillanua/jps#1]
The encapsulation is very good. I used gdi to add a gui to demonstrate, but there is a problem with the direction of the jump point. I think it is to check whether the current call is a jump point and then change the way of finding neighbors. There is also a problem of traversal. You should add "valid( current + candidate_dir"
test code
    unordered_set<Location> walls {
		{12,0},{12,1},{11,1},{11,2},{10,2},{10,3},{9,3},{9,4},{8,4},{8,5},{7,5},{7,6},
		{6,6},{6,7},{5,7},{5,8},{4,8},{4,9},{3,9},{3,10},{2,10},{2,11},{1,11},
 		{1,12},{1,13},{1,14},{2,14},{2,15},{5,6},
		{0,1},{1,0},{2,1},{3,15},{3,16}};
 	Grid map{ 22, 22, walls };

 	Location start{ 1, 1 };
 	Location goal{ 19,8 };

**Comment by QQ1598058687** [comment]
![40面向对象版表达式计算器（一）02](https://user-

**Comment by vertices-cpp** [comment]
![56faf2e9e6060bf0](https://user-images.githubusercontent.com/90932460/207864678-9ae1a035-1d78-4616-945e-d391abb3124c.png)

**Comment by hvillanua** [comment]
@QQ1598058687 Hello! I'm very happy to see that what I built is useful to others. 谢谢你的comment

I tested this locally and it works correctly, although I noticed that the test code locations don't match the ones in the attached image. Then I realized that I was running the develop branch, which contained some fixes that I did regarding the problem you're seeing, but somehow forgot to merge into the master branch.

I have now merged those and master is up to date with the latest fixes. Please test again and let me know if you encounter any other issues. Happy coding and 新年好!

**Comment by vertices-cpp** [comment]
I also debugged for a long time, and found this problem, the parent node, always jumping to the previous point, I have also fixed it now. After reading it, you have also modified it, which is great, my idea is.
:

**Comment by vertices-cpp** [comment]
![qq_pic_merged_1671203660966](https://user-images.githubusercontent.com/90932460/208129823-ed5b1724-e560-49d5-96fe-c631be6b1c46.jpg)
![qq_pic_merged_1671203681011](https://user-images.githubusercontent.com/90932460/208129852-612bf82a-85dd-4df9-9b94-f07a0bb08201.jpg)

**Comment by vertices-cpp** [comment]
nice 
![jps-1](https://user-images.githubusercontent.com/90932460/208138477-c11d20e0-e825-4934-b97c-3c83aabf800f.gif)
![QQ截图20221216235529](https://user-images.githubusercontent.com/90932460/208138515-718a836b-7883-4608-b3ca-5a0aee2d9320.png)
